Added sites Teide, CAHA, Okayama, OARMA, TNO, Calar Alto
astropy/astropy-data pull request #93
Opened 2020-06-25 08:35 UTC by japp

Just added some missing observatories, including Observatorio del Teide (Tenerife), Okayama Observatory (Japan), Calar Alto, Javalambre and OARMA (Spain) and Thai National Observatory (Thailand)

2020-07-15 09:55 UTC, japp commented
I've checked the new sites.json file using test_sites (no errors raised):                                           

In [2]: from astropy.coordinates.tests import test_sites                                                                  
In [3]: test_sites.check_builtin_matches_remote('coordinates/sites_new.json') 
In [4]:

2021-10-09 15:01 UTC, dhomeier requested changes
Thanks for extending coverage of the Eurasian hemisphere!
Looks good apart from my notes about the timezones;
maybe check if there are better sources that GoogleEarth for OARMA & OAJ as well?

2021-10-09 15:01 UTC, dhomeier commented on coordinates/sites.json
> +        "timezone": "US/Aleutian",
```suggestion
        "timezone": "US/Hawaii",
```
see #117 - should be either this or `HST`, but I think discussion there leans towards `US/Hawaii`.

2021-10-09 15:01 UTC, dhomeier commented on coordinates/sites.json
> +        "timezone": "CET",
```suggestion
        "timezone": "Europe/Madrid",
```
Again, with the discussion in https://github.com/astropy/astropy-data/issues/117#issuecomment-922374617 and `US/Hawaii`, `Atlantic/Canary` above I vote for entering all TZ consistently, so DST information is unambiguous wherever applicable.

2021-10-09 15:01 UTC, dhomeier commented on coordinates/sites.json
> +        "timezone": "CET",
```suggestion
        "timezone": "Europe/Madrid",
```

2021-10-09 15:01 UTC, dhomeier commented on coordinates/sites.json
> +        "timezone": "CET",
```suggestion
        "timezone": "Europe/Madrid",
```

2021-10-09 15:01 UTC, dhomeier commented on coordinates/sites.json
> +        "timezone": "ICT",
```suggestion
        "timezone": "Asia/Bangkok",
        "source": "TNO Wikipedia page (https://en.wikipedia.org/wiki/Thai_National_Observatory)",
```
Coordinates confirmed there, although https://www.narit.or.th/index.php/thai-national-observatory-tno-location-menu has a location ~1' to the SW...

2021-10-09 15:01 UTC, dhomeier commented on coordinates/sites.json
> +        "timezone": "JST",
```suggestion
        "latitude": 34.577075 ,
        "elevation_unit": "meter",
        "longitude": 133.5939556,
        "timezone": "Asia/Tokyo",
        "source": "OAO Website (http://www.oao.nao.ac.jp/en/telescope/abouttel188/)",
```
Note slightly different coordinates from the website location at `lat='34°34′37.47″N', lon='133°35′38.24″E'`.

No DST here, so there is no practical difference for the TZ, but I'd again recommend it for consistency (or in case Japan should ever decide to introduce it ;-).

2021-10-14 21:56 UTC, dhomeier approved these changes

2022-11-05 11:33 UTC, hamogu commented
This has been reviewed and approved a long time ago, but somehow we forgot to merge it. I'm sorry about that. If you see that happening again, feel free to prod us!

2022-11-05 11:35 UTC, merged